<?php

use Drupal\editor\Entity\Editor;

/**
 * Implements hook_form_FORM_ID_alter()
 *
 * @param $form
 * @param $form_state
 */
function macaroni_ckeditor_lightbox_form_editor_image_dialog_alter(&$form, &$form_state) {

  $editor = $form_state->getBuildInfo()['args'][0];

  if (isset($form_state->getUserInput()['editor_object'])) {
    // By convention, the data that the text editor sends to any dialog is in
    // the 'editor_object' key. And the image dialog for text editors expects
    // that data to be the attributes for an <img> element.
    $image_element = $form_state->getUserInput()['editor_object'];
    $form_state->set('image_element', $image_element);
    $form_state->setCached(TRUE);
  }
  else {
    // Retrieve the image element's attributes from form state.
    $image_element = $form_state->get('image_element') ?: [];
  }

  if($editor->getFilterFormat()->filters('filter_lightbox')->status) {

    $form['lightbox'] = [
      '#title' => t('Enable Lightbox'),
      '#type' => 'checkbox',
      '#return_value' => 'true',
      '#default_value' => $image_element['data-lightbox'],
      '#parents' => ['attributes', 'data-lightbox'],
    ];
  }

}

/**
 * Implements hook_library_info_build().
 */
function macaroni_ckeditor_lightbox_library_info_build() {

  $libraries_path = 'libraries/lightbox2';
  if (\Drupal::hasService('library.libraries_directory_file_finder')) {
    $libraries_path = \Drupal::service('library.libraries_directory_file_finder')->find('lightbox2');
  }
  elseif (function_exists('libraries_get_path')) {
    $libraries_path = libraries_get_path('lightbox2');
  }


  $libraries['lightbox2'] = [
    'js' => [
      '/' . $libraries_path . '/dist/js/lightbox.js' => ['minified' => TRUE],
    ],
    'css' => [
      'component' => [
        '/' . $libraries_path . '/dist/css/lightbox.css' => [],
      ],
    ],
  ];


  return $libraries;
}

function macaroni_ckeditor_lightbox_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'macaroni_ckeditor_lightbox/lightbox2';
}
